spring.datasource.url=jdbc:postgresql://localhost:5432/expense_splitter_db
spring.datasource.username=postgres
spring.datasource.password=4224
server.port=8088

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.hiddenmethod.filter.enabled=true
